//Cross-Site Request Forgery:
//it is an attack where a malicious site tricks a logged-in user’s browser by sending unexpected requests using users valid cookie

//if a user log in to bank website, now browser has a cookie that proves user logged in.
// user keep the bank tab open, then go to another malicious website
// That site secretly has this code inside: and sends a request to user bank
// <img src="https://mybank.com/transfer?to=hacker&amount=5000">
// users browser automatically sends bank cookie with that request bcz user logged in
// The bank sees the cookie and thinks user requested the transfer and money is stolen.

//to prevent this, we use:
//1. CSRF Token:
// A secret token is generated by the server and embedded in every page
// The server checks the token on submission.
// Malicious sites cant guess this token

//2. SameSite Cookie:
//Setting cookie attribute SameSite=Strict so cookies arent sent with cross-site reqsts

//3. Re-authentication:
// Asking the user to re-enter password/OTP